version: "3.8"
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: election-model-container
        command: ["python", "src/main.py"]
        volumes:
            - .:/app
